Implementation of ara::core::Result
UmlautSoftwareDevelopmentAccount/AP-CoreTypes pull request #53
Opened 2020-07-06 23:05 UTC by splywaczyk

2020-07-09 16:15 UTC, slci commented on include/ara/core/result.h
> +    value_type _value;
I think we should never start a symbol with an underscore.
Maybe we should document class fields using the `/**< desrciption >*/` format?

2020-07-09 16:16 UTC, slci commented on include/ara/core/result.h
> +    error_type _error;
Starting underscore.

2020-07-15 22:38 UTC, hliberacki commented on include/ara/core/result.h
> +    // TODO: This function shall not participate in overload resolution unless:
http://coliru.stacked-crooked.com/a/c81eb9a94fa788d5 here is a solution - naturally fix names ;) 

`template<class...> struct TypeList {};

template<std::size_t I, class Ts>
struct found;

template<std::size_t I, class Head, class... Tail>
struct found<I, TypeList<Head, Tail...>> : found<I - 1, TypeList<Tail...>> {};

template<class Head, class... Tail>
struct found<0, TypeList<Head, Tail...>>
{
 using type = Head;   
};

template<size_t I, class... Ts>
using T_i = found<I, TypeList<Ts...>>::type;

	
template<bool B, class T = void> using requires_ = typename std::enable_if<B, T>::type;
template<class T, class U> static constexpr bool equals_ = std::is_same_v<T, U>;
template<bool Condition> static constexpr bool not_ = !Condition;

template <class T, template <typename...> class U>
struct specialization : std::false_type {};

template <template <typename...> class U, class... Args>
struct specialization<U<Args...>, U> : std::true_type {};

template <class T, template <typename...> class U>
static constexpr bool specialization_v = specialization<T, U>::value;
template<class T, class E>
struct Result
{
    
  using value_type = T;
  
  using error_type = E; 
  template <typename... Args>
  static requires_<std::is_constructible_v<T, Args...> && 
                   not_<equals_<T, T_i<0, Args...>>> &&
                   not_<specialization_v<T_i<0, Args...>, Result>>
                   , Result> 
  FromValue(Args &&... args) { return Result{}; }  
};`

2020-07-15 22:41 UTC, hliberacki commented on include/ara/core/result.h
> +    // std::is_constructible<E, Args&&...>::value is true, and the first type of the expanded parameter pack is not E, and the
same as before but change T with E

```
template<class...> struct TypeList {};

template<std::size_t I, class Ts>
struct found;

template<std::size_t I, class Head, class... Tail>
struct found<I, TypeList<Head, Tail...>> : found<I - 1, TypeList<Tail...>> {};

template<class Head, class... Tail>
struct found<0, TypeList<Head, Tail...>>
{
 using type = Head;   
};

template<size_t I, class... Ts>
using T_i = found<I, TypeList<Ts...>>::type;

	
template<bool B, class T = void> using requires_ = typename std::enable_if<B, T>::type;
template<class T, class U> static constexpr bool equals_ = std::is_same_v<T, U>;
template<bool Condition> static constexpr bool not_ = !Condition;

template <class T, template <typename...> class U>
struct specialization : std::false_type {};

template <template <typename...> class U, class... Args>
struct specialization<U<Args...>, U> : std::true_type {};

template <class T, template <typename...> class U>
static constexpr bool specialization_v = specialization<T, U>::value;
template<class T, class E>
struct Result
{
    
  using value_type = T;
  
  using error_type = E; 
  template <typename... Args>
  static requires_<std::is_constructible_v<T, Args...> && 
                   not_<equals_<E, T_i<0, Args...>>> &&
                   not_<specialization_v<T_i<0, Args...>, Result>>
                   , Result> 
  FromValue(Args &&... args) { return Result{}; }  
};
```

2020-07-15 23:12 UTC, hliberacki commented on include/ara/core/result.h
> +    template <typename F>
This can be done like that: http://coliru.stacked-crooked.com/a/9e111827d82741d7

```
  template <typename F,
            class RT = std::invoke_result_t<F, T>,
            class Ret = std::conditional_t<specialization_v<RT, ::Result>, 
                                           RT, ::Result<RT, E>>
            >
  auto Bind(F &&f) const-> Ret {/* impl */}
```

2020-07-21 08:22 UTC, bburda commented
Any update on this?

2020-08-03 06:03 UTC, splywaczyk commented
> Any update on this?

Hi, I was on vacations but now I'm back and want to work on that issue (and hopefully finish it) this week.

2020-08-12 14:01 UTC, bburda commented on include/ara/core/result.h
> +        if ((this->hasValue_ = other.hasValue_))
Assignment in if?

2020-08-12 14:02 UTC, bburda commented on include/ara/core/result.h
> +        if ((this->hasValue_ = other.hasValue_))
Same as above.

2020-09-05 13:01 UTC, bburda requested changes

2020-09-05 22:51 UTC, hliberacki commented on include/ara/core/result.h
> +    union {
Yes, this shall be a `variant` since it's the safe union. @splywaczyk I believe we had that discussion before ;).

Using `variant` as @bburda pointed out, we would not have to care so much about some parts of the code. Please change it.

Maybe first change it to `std::variant`, I will create a task to make it as `ara::core::Variant`, and I will take care of changing it. Since if any error occurs I will fix Variant in the same time ;)

2020-09-07 06:54 UTC, splywaczyk commented on include/ara/core/result.h
> +    // FIXME: This destructor is trivial if std::is_trivially_destructible<E>::value is true.
SFINAE cannot be used for destructors as they can't be templated.
I'll check the solution with static polymorphism.

2020-09-07 06:56 UTC, splywaczyk commented on include/ara/core/result.h
> +    union {
@hliberacki - Yes we had the discussion about std::optional :)
I will switch to `std::variant`

2020-09-09 06:40 UTC, splywaczyk commented on include/ara/core/result.h
> +    // FIXME: This destructor is trivial if std::is_trivially_destructible<E>::value is true.
Switched to `std::variant` as internal representation of `Result` which implements this requirement.

2020-09-09 06:41 UTC, splywaczyk commented on include/ara/core/result.h
> +    union {
Switched to `std::variant` as internal representation of `Result` which implements this requirement.

2020-09-09 06:42 UTC, splywaczyk commented on include/ara/core/result.h
> +    Result(value_type const&& t) : value_{t}, hasValue_{true} {}
Done

2020-09-09 06:42 UTC, splywaczyk commented on include/ara/core/result.h
> +construct(Item* place, Args&&... args)
Function removed as not needed anymore.

2020-09-09 06:44 UTC, splywaczyk commented on include/ara/core/result.h
> +            }
Done

2020-09-09 06:44 UTC, splywaczyk commented on include/ara/core/result.h
> +    // FIXME: This destructor is trivial if std::is_trivially_destructible<E>::value is true.
Switched to `std::variant` as internal representation of `Result` which implements this requirement.

2020-09-09 06:46 UTC, splywaczyk commented on include/ara/core/result.h
> +    Result(Result const&& other) noexcept(
Done

2020-09-09 06:46 UTC, splywaczyk commented on include/ara/core/result.h
> +    Result(error_type const&& e) : error_{e}, hasValue_{false} {}
Done

2020-09-09 06:51 UTC, bburda requested changes
Overall It looks good, but just one more thing regarding tests. Please look at the @slci comment in #22 PR
https://github.com/UmlautSoftwareDevelopmentAccount/AP-CoreTypes/pull/22#discussion_r483620678

2020-09-10 17:01 UTC, bburda approved these changes
Looks good.

2020-09-10 19:44 UTC, hliberacki approved these changes
looks good

2020-09-10 21:31 UTC, merged